### ISSUE TITLE
raspberry pi: http ok but https responds really really slowly

### ISSUE THREAD

**Issue by benlawraus** [motasmarcelo/setup-web2py-nginx-uwsgi-debian8#1]
Hi
Method:
run setup nginx script
then run setup new script
on raspberry pi 3 with Debian Jesse

Http://192.168.0.142 produces the welcome app page
https://192.168.0.142 is very very slow, taking many many minutes to load the welcome app page, but in the end it does load.

**Comment by motasmarcelo** [comment]
Only on first hit  or all requests through https are slow?

**Comment by benlawraus** [comment]
Unfortunately, all are slow. Later I can put the raspberry pi on the public internet so you can login/see, if you think that is helpful.

**Comment by motasmarcelo** [comment]
Ok, probably it's about SSL/TLS ciphers at nginx and openssl that ships with raspberrypi. Could you try the newest version of nginx (from source)?

Edit:
Instead, you could rebuild new nginx's conf according installed versions of nginx/openssl with this helper:
https://mozilla.github.io/server-side-tls/ssl-config-generator/

give it a try and let me know your results

**Comment by motasmarcelo** [comment]
Ok, I'm closing the issue now  because it hasn't seen
any activity during the last 6 months.
